title = "QuickDirectory"

gitRepoUrl = "https://github.com/ExCodexStudios/RBX-QuickDirectory"
gitSourceBranch = "main"
changelog = true

classOrder = [
    "QuickDirectory",
    "DirConfig"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

organizationName = "ExCodexStudios"
projectName = "RBX-QuickDirectory"
url = "https://excodexstudios.github.io"
baseUrl = "/RBX-QuickDirectory/"

[footer]
style = "dark"
copyright = "ExponentialCodexStudios. 2022-2022. All Rights Reserved. Built with Moonwave and Docusarus"