title = "QuickDirectory"

gitRepoUrl = "https://github.com/ExCodexStudios/RBX-QuickDirectory"
gitSourceBranch = "main"
changelog = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

organizationName = "ExCodexStudios"
projectName = "RBX-QuickDirectory"
url = "https://excodexstudios.github.io"
baseUrl = "/RBX-QuickDirectory/"

[footer]
style = "dark"
copyright = "Copyright © 2022-2022 ExponentialCodexStudios. All Rights Reserved. Built with Moonwave and Docusarus"